### PR TITLE
Fe front page

### LINKED ISSUE #14: [Backlog] Add Front-page
Story Points: 1

front page design

Acceptance Criteria:
- [x] The frontpage should be simple and clean, not cluttered.
- [x] The frontpage should have a way to go to the next page (map/activity page)

# User stories
- As a visitor of the website, I can go to the map, such that I can view the venues.
- As a visitor, I can read what the project is about on the frontpage, so that I know what I can use the service for.

### PR DESCRIPTION
**Pull request by killje**
Created front page

Closes #14

### CODE REVIEW

**Comment by killje** [comment]
Closes #27

**Comment by Producermark** [comment]
Also, frontend\package-lock.json is being updated on my part, which should be added to the gitignore (as this should be different per dev environment)

**Comment by killje** [comment]
@Producermark I can not reproduce the problems the menu navigates without problems. Maybe you are in the menu branch that does not have the frontpage

**Comment by killje** [comment]
Package lock should be uploaded as the dev environment should NOT be different

**Comment by Producermark** [comment]
In case it should not be different, the following happens:

- You install a new package
- The new package gets added to the package.json and the lock file.
- You commit.
- I pull the new lock and package file.
- I run npm install. It reads the lock file and it concludes that the new packages are already installed or “locked”, so I don’t get the new packages. You do, because it’s your lock file

**Comment by killje** [comment]
No the lock file is a full tree of packages, while the package file is only the top dependencies.

So when you do npm install it sees there is a lock file and uses that to download the given versions in that, otherwise it uses the versions of dependencies in the top dependencies

**Comment by killje** [comment]
The lock file has nothing to do with stuff already being installed

**Comment by killje** [comment]
eg:
you have dep A that uses a dep itself called dep B version 1.2 and onward.

now dep B is updated to 1.3, someone else uses the project as well, when they now install they will have dep B v1.3. so two people have different versions while nothing in the project has changed.

This is where the package lock comes into play. It says that even if B updates you need to use the specified version 1.2 so both people have the same envoirment

**Pull request merged**
